version: 1.0.{build}
branches:
  only:
    - master
    - /v?\d+\.\d+\.\d+/
configuration: Release
platform: x86
before_build:
  - git submodule update --init --recursive
  - git clone https://github.com/andburn/powershell.git C:\projects\build\Powershell
  - ps: .\Scripts\bootstrap.ps1
  - ps: .\Scripts\appveyor.ps1 VictoryShot -PreBuild
build:
  project: VictoryShot.sln
  verbosity: minimal
after_build:
  - ps: .\Scripts\appveyor.ps1 VictoryShot -PostBuild
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: Update $(APPVEYOR_REPO_TAG_NAME)
    description: Description
    auth_token:
      secure: OpNj+lrWxBC7mLLsC2F7BqFrwrOBXsgqelz6t0wK8pqIBjO7Imn9Adp+k6OuNbCN
    artifact: Release
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
